# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAddToCart():

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
    
  def test_addtoCart_button(self):
    self.driver.get("https://www.saucedemo.com")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"password\"]").send_keys("secret_sauce")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"login-button\"]").click()
    
    button = self.driver.find_element(
      By.ID,
      "add-to-cart-sauce-labs-backpack"
    )

    button.click()

    remove_button = self.driver.find_element(
      By.ID,
      "remove-sauce-labs-backpack"
    )

    # Test the button with correct ID exists
    assert remove_button
    # Test that it says "Remove"
    assert remove_button.text == "Remove"

  def test_addtoCart_inCart(self):
    self.driver.get("https://www.saucedemo.com")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"password\"]").send_keys("secret_sauce")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"login-button\"]").click()
    button = self.driver.find_element(
      By.ID,
      "add-to-cart-sauce-labs-backpack"
    )
    button.click()
    
    self.driver.find_element(
      By.CSS_SELECTOR, "[data-test=\"shopping-cart-badge\"]"
      ).click()
    
    item_in_cart = self.driver.find_element(
      By.CSS_SELECTOR, "[data-test=\"inventory-item-name\"]"
      )
    
    # Test correct item in cart
    assert item_in_cart
    assert item_in_cart.text == "Sauce Labs Backpack"