# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC


class TestLogin():

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_runtime_login_1s(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"username\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"password\"]").send_keys("secret_sauce")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"login-button\"]").click()
    
    start = time.perf_counter()
    if "inventory.html" in self.driver.current_url and self.driver.find_element(By.CLASS_NAME, "title").text == "Products":
      end = time.perf_counter()
      runtime = end-start
      assert runtime < 1.0

  def test_runtime_logout_1s(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"username\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"password\"]").send_keys("secret_sauce")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"login-button\"]").click()
    self.driver.find_element(By.ID, "react-burger-menu-btn").click()
    # Wait until the logout link is clickable
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "[data-test='logout-sidebar-link']"))).click()
    start = time.perf_counter()
    if self.driver.find_element(By.CLASS_NAME, "login-box"):
      end = time.perf_counter()
      runtime = end-start
      assert runtime < 1.0