# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestCompatibilitys():

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_compatibility(self):
    self.driver.get("https://www.saucedemo.com/")
    time.sleep(3)
    assert self.driver.find_element(By.CLASS_NAME, "login-box")
    self.driver.close()

    self.driver = webdriver.Firefox()
    self.driver.get("https://www.saucedemo.com/")
    time.sleep(3)
    assert self.driver.find_element(By.CLASS_NAME, "login-box")
    self.driver.close()
 
    self.driver = webdriver.Edge()
    self.driver.get("https://www.saucedemo.com/")
    time.sleep(3)
    assert self.driver.find_element(By.CLASS_NAME, "login-box")
    self.driver.close()
    